// Generated by Wrangler by running `wrangler types`

interface Env {
  CORS_ALLOW_ORIGIN: string;
  LIVE_PROD_JWT_PUBKEY: string;
  SANDBOX_PROD_JWT_PUBKEY: string;
  LIVE_INT_JWT_PUBKEY: string;
  SANDBOX_INT_JWT_PUBKEY: string;
  LIVE_DEV_JWT_PUBKEY: string;
  SANDBOX_DEV_JWT_PUBKEY: string;
  IS_PROD: boolean;
  HELIUS_API_KEY: string;
}
